apiVersion: v1
kind: ConfigMap
metadata:
  name: my-nginx-config
  namespace: nginx-app
data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 1024; }
    http {
        server {
            listen 80;
            location / { # Отдаёт статический контент из /usr/share/nginx/html
                root /usr/share/nginx/html; 
                index index.html;
            }

            location /metrics { # Теперь nginx отдаёт метрики по http://localhost/metrics, но они не в Prometheus-формате, поэтому нужен экспортер под
                stub_status;
                allow all;  # Разрешаем доступ ко всем метрикам
            }
        }
    }